# Generated by Django 2.1.5 on 2019-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='selling_price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_remains',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
