# Generated by Django 2.1.5 on 2019-02-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomerbill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.BillHistory')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('total_price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbills',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='userbills',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='userbills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserBills',
        ),
        migrations.AddField(
            model_name='customerbill',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Bill'),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Customer'),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Shop'),
        ),
    ]
