# Generated by Django 2.1.5 on 2019-02-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(max_length=100),
        ),
    ]
