# Generated by Django 2.1.5 on 2019-02-05 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190205_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_reamins',
            new_name='minimum_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_remains',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
