# Generated by Django 2.1.5 on 2019-02-08 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190208_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_expense', models.FloatField(default=0)),
                ('travel_expense', models.FloatField(default=0)),
                ('additional_expense', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop')),
            ],
        ),
    ]
